site_name: "DevHub Content Template Test Documentation"
site_description: "Documentation to show how the DevHub Content Template works"
docs_dir: "docs"
plugins:
    - techdocs-core
    - ezlinks
markdown_extensions:
    - markdown_inline_mermaid
    - md_in_html
    -   mkpatcher:
            location: patcher.py
